name : Run Shell Commands 
on : [push]

jobs:
 run-shell-commands:
   runs-on: ubuntu-latest
   steps:
       - name: Echo a String
         run: echo "Hello Security guru!! This is the first github action to run shell commands"
